# Main directories to search for sessions
TS_SEARCH_PATHS=("$HOME")

# Optional extra paths with depth
TS_EXTRA_SEARCH_PATHS=("$HOME/esoft/:2",)
TS_EXTRA_SEARCH_PATHS=("$HOME/.config:2",)
TS_EXTRA_SEARCH_PATHS=("$HOME/personal/love2d/:2",)
TS_EXTRA_SEARCH_PATHS=("$HOME/personal/dev/:2",)

# Default max search depth
TS_MAX_DEPTH=2
