set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#7750d9 fg=#000000'

set -g status-right '#(date +"%a-%d-%b-%m") | #(echo $XDG_CURRENT_DESKTOP) | luth '

bind r source-file ~/.tmux.conf \; display-message -d 2000 "Configuration reloaded!"
set -g base-index 1

set -g message-style "fg=black,bg=#5d26ab"

set -gq allow-passthrough on
set -g visual-activity off

bind v copy-mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

# tmux doesnt close on session close
set-option -g detach-on-destroy off

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Kill pane without confirmation (prefix + x)
unbind x
bind x kill-pane

# Kill window without confirmation (prefix + &)
unbind &
bind & kill-window

bind a choose-session

bind q switch-client -l

# Create a key table for splits
bind s switch-client -T split

# Bind keys in the 'split' table
bind -T split l split-window -h -c "#{pane_current_path}"   # l = horizontal/right
bind -T split j split-window -v -c "#{pane_current_path}"   # j = vertical/down

bind-key t run-shell "~/.local/bin/kitty-transparency.lua"

# todo
bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim "$HOME/Documents/todo.md""

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key -r i run-shell "tmux neww tmux-cht.sh"

bind-key -r H if-shell "tmux has-session -t 0" \
  "switch-client -t 0" \
  "new-session -s 0"

bind-key -r G run-shell "~/.local/bin/tmux-sessionizer ~/esoft/"
