# no tab bar
tab_bar_edge none
tab_bar_style hidden

# transparency
dynamic_background_opacity yes
background_opacity 0.8

# colors
background #000000
foreground #e8d7fc

# cursor
# cursor_trail 1
cursor     #c499f3
cursor_blink_interval 0

# font
font_family CaskaydiaCove Nerd Font
font_size 12.0

# disable window close confirmation
confirm_os_window_close 0

# enable remote control
allow_remote_control yes
